# NumPy Operations
___

## Arithmetic
* Array arithmetic or scalar with array arithmetic

In [5]:
import numpy as np
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
# Combine the values of two arrays
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [11]:
b - a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [13]:
# Scalar operation
a + 47

array([47, 48, 49, 50, 51, 52, 53, 54, 55, 56])

In [14]:
b - 237

array([-227, -226, -225, -224, -223, -222, -221, -220, -219, -218])

In [17]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [15]:
# Warning: Invalid value --> nan
a/a

C:\Users\likre\AppData\Local\Temp\ipykernel_33184\3670270827.py:2: RuntimeWarning: invalid value encountered in divide
  a/a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
# Warning: Infinity --> inf
1/a

C:\Users\likre\AppData\Local\Temp\ipykernel_33184\3900290995.py:2: RuntimeWarning: divide by zero encountered in divide
  1/a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
# Warning message on division by zero. Message will show: nan
a/a

In [ ]:
# Infinity warning message --> RuntimeWarning: divide by zero encountered in divide
1/a

___
## Universal Array Functions
* Numpy includes many universal array functions
* Universal array functions allows mathematical operations to be performed across the array

In [18]:
#Taking Square Roots
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [19]:
#Calcualting exponential (e^)
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [20]:
np.max(a) #same as a.max()

9

In [21]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [23]:
# Warning: Log of 0 --> Negative infinity
np.log(a)

C:\Users\likre\AppData\Local\Temp\ipykernel_33184\631991069.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])